workflows:
  Zeus-workflow:
    name: Zeus Legacy
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Zeus API
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.Zeus-Legacy.Zeus-Legacy
      vars:
        BUNDLE_ID: "com.Zeus-Legacy.Zeus-Legacy"
        XCODE_SCHEME: "Unity-iPhone"
        APP_STORE_APPLE_ID: 6771004417
      xcode: latest
    scripts:
      - name: Set up provisioning profiles
        script: xcode-project use-profiles
      
      - name: Fix missing Unity files
        script: |
          mkdir -p Classes/PluginBase UnityFramework
          
          # Header files
          touch Classes/PluginBase/LifeCycleListener.h
          touch Classes/PluginBase/RenderPluginDelegate.h
          touch Classes/PluginBase/UnityViewControllerListener.h
          touch Classes/PluginBase/AppDelegateListener.h
          touch Classes/UnityAppController.h
          touch Classes/RedefinePlatforms.h
          touch Classes/UndefinePlatforms.h
          touch UnityFramework/UnityFramework.h
          
          # PCH file
          touch Classes/Prefix.pch
          
          # Plist files
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleDevelopmentRegion</key>
              <string>en</string>
              <key>CFBundleExecutable</key>
              <string>UnityFramework</string>
              <key>CFBundleIdentifier</key>
              <string>com.Zeus-Legacy.Zeus-Legacy</string>
              <key>CFBundleInfoDictionaryVersion</key>
              <string>6.0</string>
              <key>CFBundleName</key>
              <string>UnityFramework</string>
              <key>CFBundlePackageType</key>
              <string>FMWK</string>
              <key>CFBundleShortVersionString</key>
              <string>1.0</string>
              <key>CFBundleVersion</key>
              <string>1</string>
          </dict>
          </plist>' > UnityFramework/Info.plist
          
          echo '{}' > UnityFramework/PrivacyInfo.xcprivacy
      
      - name: Increment build number
        script: |
          cd "$CM_BUILD_DIR"
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "Unity-iPhone.xcodeproj" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
